#!/usr/bin/env python3
"""
PRISM End-to-End Pipeline: Protocol Planning -> Protocol Generation -> Simulation Validation

Chains Stage 1 (ProtocolPlanner/run_stage1.py) and Stage 2 (ProtocolGenerator/Code/run_agent.sh)
to produce a fully validated, simulation-tested protocol from a high-level experiment request.

This script automates the Stage 1 -> Stage 2 handoff that was previously manual.

Usage:
    # Full end-to-end: PCR with GPT-5, multi-agent constrained
    python run_prism.py --experiment pcr --paradigm constrained --model gpt-5

    # Full end-to-end: PCR with Claude Opus, open-ended
    python run_prism.py --experiment pcr --paradigm open-ended --model claude-opus

    # Stage 1 only (no simulation)
    python run_prism.py --experiment pcr --paradigm constrained --model gpt-5 --stage1-only

    # Stage 2 only (reuse existing Stage 1 output)
    python run_prism.py --experiment pcr --stage2-only path/to/final_protocol.txt
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Lab-specific context that bridges Stage 1 (abstract protocol) to Stage 2
# (physical lab with specific instruments, deck positions, and programs).
#
# Stage 1 produces structured liquid-handling steps + thermocycling parameters.
# Stage 2 needs those PLUS physical lab setup and post-liquid-handling steps
# (seal, thermocycle with a program number, peel, plate reader, etc.).
# ---------------------------------------------------------------------------
LAB_CONTEXT = {
    "pcr": {
        "setup": (
            "The `ot2bioalpha` OT-2 is prepared with the 96-well plates "
            "`react_plate` at deck position 3 and `dest_plate` at deck position 1"
        ),
        "post_steps": [
            "Mix 10X with pipette set to 20 uL in all destination wells used above",
            "Seal the plate to prepare it for thermocycling",
            "Perform a thermocycling operation (program #5)",
            "Peel the plate to prepare it for reading",
            'Perform an absorbance reading using the Hidex plate reader (protocol "PCR_Final_Results")',
            "Open the Hidex plate reader lid after analysis completion",
        ],
    },
}


def run_stage1(args, output_dir: Path) -> Path:
    """Run Stage 1 (Protocol Planning) and return path to final_protocol.txt."""
    stage1_dir = output_dir / "stage1"
    cmd = [
        sys.executable,
        str(REPO_ROOT / "ProtocolPlanner" / "run_stage1.py"),
        "--experiment", args.experiment,
        "--paradigm", args.paradigm,
        "--model", args.model,
        "--mode", args.mode,
        "--temperature", str(args.temperature),
        "--max-iterations", str(args.max_iterations),
        "--output-dir", str(stage1_dir),
    ]
    if args.model_id:
        cmd += ["--model-id", args.model_id]

    print("=" * 60)
    print("STAGE 1: Protocol Planning")
    print("=" * 60)

    result = subprocess.run(cmd)
    if result.returncode != 0:
        print(f"\nError: Stage 1 failed with exit code {result.returncode}")
        sys.exit(1)

    final_protocol = stage1_dir / "final_protocol.txt"
    if not final_protocol.exists():
        print(f"\nError: Stage 1 did not produce {final_protocol}")
        sys.exit(1)

    print(f"\nStage 1 output: {final_protocol}")
    return final_protocol


def format_workflow(stage1_output: Path, experiment: str, output_dir: Path) -> Path:
    """Convert Stage 1 output into a Stage 2 workflow description file.

    Adds lab-specific context (deck positions, instrument names) and
    post-liquid-handling physical steps (seal, thermocycle, peel, read)
    that Stage 1 does not produce.
    """
    protocol_text = stage1_output.read_text().strip()

    if experiment not in LAB_CONTEXT:
        print(f"Error: No lab context defined for experiment '{experiment}'.")
        print(f"Available: {', '.join(LAB_CONTEXT.keys())}")
        sys.exit(1)

    lab = LAB_CONTEXT[experiment]

    lines = [
        "# Workflow",
        "",
        "These are the high-level workflow steps for this experiment, "
        "generated by PRISM Protocol Planning (Stage 1).",
        "",
        lab["setup"],
        "",
        protocol_text,
        "",
    ]

    # Append post-liquid-handling steps
    if lab.get("post_steps"):
        lines.append("## Post-Liquid-Handling Steps")
        lines.append("")
        lines.append(
            "After all liquid handling and thermocycling steps above, "
            "perform the following physical workflow steps:"
        )
        lines.append("")
        for i, step in enumerate(lab["post_steps"], 1):
            lines.append(f"{i}.) {step}")
        lines.append("")

    workflow_path = output_dir / "stage2_workflow.md"
    workflow_path.write_text("\n".join(lines))
    print(f"Stage 1 -> Stage 2 workflow file: {workflow_path}")
    return workflow_path


def run_stage2(workflow_file: Path):
    """Run Stage 2 (Protocol Generation + Simulation Validation)."""
    print("\n" + "=" * 60)
    print("STAGE 2: Protocol Generation + Simulation Validation")
    print("=" * 60)

    stage2_dir = REPO_ROOT / "ProtocolGenerator" / "Code"
    run_agent = stage2_dir / "run_agent.sh"

    if not run_agent.exists():
        print(f"Error: run_agent.sh not found at {run_agent}")
        sys.exit(1)

    # Use absolute path so it works from any cwd
    workflow_abs = str(workflow_file.resolve())

    cmd = ["bash", str(run_agent), workflow_abs]
    result = subprocess.run(cmd, cwd=str(stage2_dir))
    if result.returncode != 0:
        print(f"\nError: Stage 2 failed with exit code {result.returncode}")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="PRISM End-to-End: Protocol Planning -> Generation -> Simulation",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Stage 1 arguments
    parser.add_argument(
        "--experiment", choices=["pcr", "cellpainting"],
        help="Experiment type",
    )
    parser.add_argument("--paradigm", help="Prompting paradigm (e.g. constrained, open-ended, fixed)")
    parser.add_argument("--model", help="LLM model (e.g. gpt-5, claude-opus, gemini-pro)")
    parser.add_argument("--model-id", help="Override the model ID sent to the API")
    parser.add_argument(
        "--mode", default="multi-agent", choices=["multi-agent", "single-agent"],
        help="Pipeline mode (default: multi-agent)",
    )
    parser.add_argument("--max-iterations", type=int, default=3, help="Max Critique/Validator iterations (default: 3)")
    parser.add_argument("--temperature", type=float, default=0.7, help="LLM sampling temperature (default: 0.7)")

    # Pipeline control
    parser.add_argument("--output-dir", help="Output directory (auto-generated if not set)")
    parser.add_argument("--stage1-only", action="store_true", help="Run Stage 1 only, skip simulation")
    parser.add_argument(
        "--stage2-only", metavar="PROTOCOL_FILE",
        help="Skip Stage 1, use an existing final_protocol.txt for Stage 2",
    )

    args = parser.parse_args()

    # --- Validate arguments ---
    if args.stage2_only:
        # Only need --experiment for lab context
        if not args.experiment:
            parser.error("--experiment is required even with --stage2-only (needed for lab context)")
        stage1_output = Path(args.stage2_only)
        if not stage1_output.exists():
            parser.error(f"File not found: {args.stage2_only}")
    else:
        if not all([args.experiment, args.paradigm, args.model]):
            parser.error("--experiment, --paradigm, and --model are required (or use --stage2-only)")

    # --- Output directory ---
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        label = f"e2e_{args.experiment}"
        if not args.stage2_only:
            label += f"_{args.paradigm}_{args.model}"
        output_dir = REPO_ROOT / "outputs" / f"{label}_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=True)

    # Save run config
    run_config = {
        "experiment": args.experiment,
        "paradigm": getattr(args, "paradigm", None),
        "model": getattr(args, "model", None),
        "mode": args.mode,
        "stage1_only": args.stage1_only,
        "stage2_only": args.stage2_only,
        "timestamp": datetime.now().isoformat(),
    }
    (output_dir / "run_config.json").write_text(json.dumps(run_config, indent=2))

    print("=" * 60)
    print("PRISM End-to-End Pipeline")
    print("=" * 60)
    print(f"  Experiment:  {args.experiment}")
    if not args.stage2_only:
        print(f"  Paradigm:    {args.paradigm}")
        print(f"  Model:       {args.model}")
        print(f"  Mode:        {args.mode}")
    print(f"  Output:      {output_dir}")
    print("=" * 60)

    # --- Stage 1 ---
    if args.stage2_only:
        stage1_output = Path(args.stage2_only)
        print(f"\nSkipping Stage 1, using existing output: {stage1_output}")
    else:
        stage1_output = run_stage1(args, output_dir)

    if args.stage1_only:
        print(f"\n{'=' * 60}")
        print(f"Stage 1 complete. Output: {stage1_output}")
        print(f"{'=' * 60}")
        print(f"\nTo continue to Stage 2 later:")
        print(f"  python run_prism.py --experiment {args.experiment} --stage2-only {stage1_output}")
        return

    # --- Bridge: Format Stage 1 output for Stage 2 ---
    workflow_file = format_workflow(stage1_output, args.experiment, output_dir)

    # --- Stage 2 ---
    run_stage2(workflow_file)

    print("\n" + "=" * 60)
    print("PRISM End-to-End Pipeline Complete")
    print(f"  All outputs: {output_dir}/")
    print("=" * 60)


if __name__ == "__main__":
    main()
